server:
  port: 18085

spring:
  datasource:
    url: jdbc:mysql://${mysql.host}:${mysql.port}/snow_system?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true

mybatis-plus:
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 30000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 30000 #服务请求处理超时时间（毫秒）