version: '3'
services:
  snow-gateway:
    image: snow/snow-gateway:0.0.1-SNAPSHOT
    container_name: snow-gateway
    ports:
      - 18080:18080
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
  snow-auth:
    image: snow/snow-auth:0.0.1-SNAPSHOT
    container_name: snow-auth
    ports:
      - 18085:18085
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
  snow-system:
    image: snow/snow-system:0.0.1-SNAPSHOT
    container_name: snow-system
    ports:
      - 18082:18082
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
  snow-meta:
    image: snow/snow-meta:0.0.1-SNAPSHOT
    container_name: snow-meta
    ports:
      - 18083:18083
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
  snow-job:
    image: snow/snow-job:0.0.1-SNAPSHOT
    container_name: snow-job
    ports:
      - 18083:18083
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'